jobs:
- job: VCPKGbuild
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 360
  steps:
  - checkout: self
    submodules: recursive
  - task: CopyFiles@2
    inputs:
      targetFolder: '$(Build.StagingDirectory)\_'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call initvcpkg.cmd
    displayName: Build ROS2.net dependencies
    workingDirectory: '$(Build.StagingDirectory)\_'
  - script: |
      mkdir %Build_ArtifactStagingDirectory%\zip
      7z a -tzip %Build_ArtifactStagingDirectory%\zip\vcpkg.zip c:\opt\vcpkg -v512m
    displayName: Create VCPKG Archive
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)\zip
      artifactName: 'ros2vcpkg'
    displayName: Publish vcpkg
